
debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    kr.hankyungsoo.admin: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.web.client.RestTemplate: debug
spring:
  devtools:
    livereload:
      port: 35730
  datasource:
    url: jdbc:mysql://localhost:3306/admin
    username: hanks
    password: 590405
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  messages:
    basename: errors
  sql:
    init:
      mode: always
  thymeleaf3:
    decoupled-logic: true
server:
  port: 8080

project.board.url: http://localhost:9090
